version: '3.1'

services:
  frontend:
    build: frontend/
    ports:
      - 4200:80

  backend:
    build: backend/
    ports:
      - 8000:8080

  db:
    build: db/
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rigjeiorr4353I
    ports:
      - 33061:3306